python3 main.py diabetes.csv
python3 main.py iris.csv
python3 main.py diabetes.csv
python3 main.py iris.csv
python3 main.py diabetes.csv
python3 main.py iris.csv
python3 main.py diabetes.csv
python3 main.py iris.csv
python3 main.py diabetes.csv
python3 main.py iris.csv
